runtime: python37

handlers:
- url: /
  static_files: static/solar-chart/index.html
  upload: static/solar-chart/index.html
- url: /(.*)
  static_files: static/solar-chart/\1
  upload: static/solar-chart/(.*)

